language: node_js

node_js:
  - '12'

cache:
  directories:
    - node_modules
    - ~/.npm

git:
  depth: 3

script:
  - yarn build

notifications:
  email:
    recipients:
      - franjavikale@gmail.com
    on_success: always
    on_failure: always

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

deploy:
  provider: pages
  skip-clean: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: '[DEPLOY] New Version on Travis-ci'
  on:
    branch: master